### ISSUE TITLE
editing the bashrd-file

### ISSUE THREAD

**Issue by SimonAM** [OliPelz/spreads-ubuntu-trusty#1]
Hi! 
And thank you for a fantastic guide to installing spreads on ubuntu!
When editing the .bashrc file
I enter it like this in the top of the file:

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export CHDKPTP_DIR=/usr/local/lib/chdkptp
export LUA_PATH="$CHDKPTP_DIR/lua/?.lua"
source ~/.spreads/bin/activate

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

```

Correct? When running 

```
spread configure 
```

and choosing the chdkptp driver, it does not find the driver. 
Any ideas on what is wrong?

**Comment by OliPelz** [comment]
Hi Simon,

Have you relogged in to the shell or resourced .bashrc before running spreads?

``` bash
source ~/.bashrc
```

What is the output of

``` bash
echo $CHDKPTP_DIR
echo $LUA_PATH
```

**Comment by SimonAM** [comment]
The output is correct, i.e.

```
usr/local/lib/chdkptp
#and
/usr/local/lib/chdkptp/lua?.lua
```

I dont know what it means to relog into the shell. 
I have re-run your instructions multiple times from the point where:

"finally install spreads in an virtualenv, create a new one"

```
virtualenv ~/.spreads
source ~/.spreads/bin/activate
```

Further down the script, i always use the command:

```
source ~/.bashrc
```

Will re-install ubuntu and try again.

**Comment by SimonAM** [comment]
Ok, reinstalled ubuntu. 
First error at:

```
sudo gem install pdfbeads
```

Gives the following error message:

```
Fetching: rmagick-2.15.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing pdfbeads:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for gcc... yes
checking for Magick-config... yes

Warning: Found a partial ImageMagick installation. Your operating system likely has some built-in ImageMagick libraries but not all of ImageMagick. This will most likely cause problems at both compile and runtime.
Found partial installation at: /usr
checking for outdated ImageMagick version (<= 6.4.9)... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

```

```
Gem files will remain installed in /var/lib/gems/1.9.1/gems/rmagick-2.15.3 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/rmagick-2.15.3/ext/RMagick/gem_make.out

```

**Comment by OliPelz** [comment]
Dear Simon,

Whats your ubuntu version you try to install spreads onto?

**Comment by SimonAM** [comment]
It is 14.04 LTS. I installed it from USB without an internet connection.

**Comment by OliPelz** [comment]
mmhh maybe newer pdfbeads version has more image magick dependencies than one years ago, can you try to install the following (before trying to install pdfbeads again)? :

``` bash
sudo apt-get install imagemagick libmagickcore-dev
```

(taken from http://stackoverflow.com/questions/9992336/installing-rmagick-2-13-1-with-graphicsmagick-on-ubuntu-10-04)

**Comment by SimonAM** [comment]
Thanks for helping! 
I'll try it out.

**Comment by SimonAM** [comment]
It worked. pdfbeads installed without any errors. 
But when installing djvubind i get som problems

```
simon@thecomputer:~$ sudo dpkg -i djvubind_1.2.1.deb
Selecting previously unselected package djvubind.
(Reading database ... 173233 files and directories currently installed.)
Preparing to unpack djvubind_1.2.1.deb ...
Unpacking djvubind (1.2.1) ...
dpkg: dependency problems prevent configuration of djvubind:
 djvubind depends on djvulibre-bin; however:
  Package djvulibre-bin is not installed.
 djvubind depends on tesseract-ocr; however:
  Package tesseract-ocr is not installed.

dpkg: error processing package djvubind (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 djvubind

```

**Comment by OliPelz** [comment]
Dear Simon,

This error is normal!

dpkg is just for installing singe packages and cannot resolve dependencies. 
Therefore as stated in my manual use afterwards:

``` bash
sudo apt-get -f install
```

which will install all the dependencies.

Than once again run 

``` bash
sudo dpkg -i djvubind_1.2.1.deb
```

see my original installation instruction at:

``` bash
wget http://djvubind.googlecode.com/files/djvubind_1.2.1.deb
sudo dpkg -i djvubind_1.2.1.deb
sudo apt-get -f install
sudo dpkg -i djvubind_1.2.1.deb
```

I should update the instructions to make it more clear!

**Comment by SimonAM** [comment]
Ok, thanks!
I went through the script but it didnt work. 

```
Selected "chdkcamera" as device driver
spreads encountered an error:
Traceback (most recent call last):
  File "/home/simon/.spreads/local/lib/python2.7/site-packages/spreads/main.py", line 321, in main
    run()
  File "/home/simon/.spreads/local/lib/python2.7/site-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/home/simon/.spreads/local/lib/python2.7/site-packages/spreads/cli.py", line 203, in configure
    driver = plugin.get_driver(config["driver"].get())
  File "/home/simon/.spreads/local/lib/python2.7/site-packages/spreads/plugin.py", line 457, in get_driver
    .format(driver_name, err.message[16:]), driver_name)
ExtensionException: Missing dependency for driver 'chdkcamera': chdkptp

```

I have also tried the guide at http://spreads.readthedocs.org/en/latest/tutorial.html to no avail. 
I have had the scanner for 2.5 years but have only used the command line interface, would be nice to get this to work!

**Comment by OliPelz** [comment]
Dear Simon,

You should get it to work soon :)

I think you have the same problem as described here: https://github.com/DIYBookScanner/spreads/issues/162
Solution should be:

``` bash
$ sudo apt-get install liblua5.2-dev
$ pip install --install-option='--no-luajit' lupa
$ pip install chdkptp.py
```

sorry for the confusions but spreads and its dependencies have been developed further so there are library and version changes all over....I definetely have to update my docs some time to catch all those new version issues when I find the time.

**Comment by SimonAM** [comment]
You are the best!
Now i have used spreads for the first time!
I have forked you repo and will commit some minor changes. 
Spreads couldn't find the cameras at first, Do you think using the keyboard and mouse when setting up cameras can interupt it?

Kind regards
Simon

**Comment by OliPelz** [comment]
Dear Simon,

No problem! Glad it worked out at the end for you.
Great idea to fork and improve the instructions, just give me a note when its ready so I can merge it too here.
Using keyboard and mouse should not interrupt the cameras, have you killed the gphoto2 process?
Is it still running? , try

``` bash
ps aux | grep -i gphoto
```

Here is an instruction on how to disable gphoto2 permanently, maybe we have to validate and put this into the instructions as well:
https://github.com/markvdb/diybookscanner/wiki/Software-triggering-on-Debian-GNU-Linux#avoiding-competition-for-our-cameras

**Comment by SimonAM** [comment]
Yes, the instructions for disabling gphoto2 worked. Got some error messages but after reboot gphoto2 is still deactivated.
